import {
  aboutContent,
  blogPosts,
  company,
  industries,
  navLinks,
  services,
  stats,
  whyUsPoints,
} from '@/data/placeholder'
import { images } from '@/data/images'
import type { BlogPostRow, NavLink, PageSection, SiteSettings } from '@/types/cms'

export function getDefaultSiteSettings(): SiteSettings {
  return {
    id: 'demo',
    company_name: company.name,
    company_short_name: company.shortName,
    slogan: company.slogan,
    tagline: company.tagline,
    founded: company.founded,
    email: company.email,
    phone: company.phone,
    phone_raw: company.phoneRaw,
    address: company.address,
    city: company.city,
    working_hours: company.workingHours,
    map_embed_url: company.mapEmbedUrl,
    site_url: import.meta.env.VITE_SITE_URL ?? null,
    logo_url: '/logo.png',
    logo_subtitle: 'İş Güvenliği',
    favicon_url: '/favicon.png',
    footer_tagline: null,
    footer_copyright: null,
    instagram_url: null,
    linkedin_url: null,
    ga4_measurement_id: import.meta.env.VITE_GA4_ID ?? null,
    gtm_container_id: import.meta.env.VITE_GTM_ID ?? null,
    google_site_verification: null,
    default_meta_title_suffix: company.name,
    default_meta_description: `${company.name} - ${company.slogan}`,
    default_og_image_url: images.banners.about,
    default_meta_robots: 'index,follow',
    nav_links: navLinks as NavLink[],
    updated_at: new Date().toISOString(),
  }
}

export function getDefaultPageSections(): PageSection[] {
  return [
    {
      id: 'demo-hero',
      page: 'home',
      section_key: 'hero',
      data: { badge: 'Kurumsal tedarik', trustItems: ['CE / TSE uyumlu', '48 saat sevkiyat', '15+ yıl deneyim'] },
      sort_order: 1,
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-stats',
      page: 'home',
      section_key: 'stats',
      data: { items: stats },
      sort_order: 2,
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-services',
      page: 'home',
      section_key: 'services',
      data: { eyebrow: 'Hizmetlerimiz', title: 'İhtiyacınıza uygun tedarik alanları', items: services },
      sort_order: 3,
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-why',
      page: 'home',
      section_key: 'why_us',
      data: {
        eyebrow: 'Neden Doğan?',
        title: 'Kurumsal tedarikte güvenilir ortak',
        description: 'Temizlik ve iş güvenliği ihtiyaçlarınızı tek noktadan karşılıyoruz.',
        points: whyUsPoints,
      },
      sort_order: 4,
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-industries',
      page: 'home',
      section_key: 'industries',
      data: { eyebrow: 'Sektörler', title: 'Hizmet verdiğimiz alanlar', items: industries },
      sort_order: 5,
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-categories',
      page: 'home',
      section_key: 'categories',
      data: {
        eyebrow: 'Ürün Kategorileri',
        title: 'İhtiyacınıza göre keşfedin',
        items: [
          {
            title: 'Temizlik Malzemeleri',
            slug: 'temizlik-malzemeleri',
            description: 'Endüstriyel deterjan, hijyen ve zemin bakım ürünleri',
            image: images.services.cleaning,
            icon: 'Sparkles',
            count: '250+ ürün',
          },
          {
            title: 'İş Güvenliği Ekipmanları',
            slug: 'is-guvenligi-ekipmanlari',
            description: 'KKD, baret, eldiven, yelek ve iş ayakkabıları',
            image: images.services.safety,
            icon: 'Shield',
            count: '250+ ürün',
          },
        ],
      },
      sort_order: 5,
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-cta',
      page: 'home',
      section_key: 'cta',
      data: {
        title: 'Kurumsal tedarik için iletişime geçin',
        description: 'Ürün kataloğumuzu inceleyin veya teklif alın.',
        primaryLabel: 'Kataloğu İncele',
        secondaryLabel: 'İletişime Geç',
        image: images.cta,
      },
      sort_order: 6,
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-about',
      page: 'about',
      section_key: 'main',
      data: aboutContent,
      sort_order: 1,
      updated_at: new Date().toISOString(),
    },
    {
      id: 'demo-contact',
      page: 'contact',
      section_key: 'main',
      data: {
        subtitle: 'Sorularınız ve teklif talepleriniz için bize ulaşın.',
        successMessage: 'Mesajınız alındı. En kısa sürede dönüş yapacağız.',
      },
      sort_order: 1,
      updated_at: new Date().toISOString(),
    },
  ]
}

export function getDefaultBlogPosts(): BlogPostRow[] {
  return blogPosts.map((p, i) => ({
    id: `demo-blog-${i}`,
    slug: p.slug,
    title: p.title,
    excerpt: p.excerpt,
    content: p.content,
    image_url: p.image,
    image_urls: p.image ? [p.image] : [],
    category: p.category,
    published_at: p.publishedAt,
    read_time: p.readTime,
    is_published: true,
    meta_title: p.title,
    meta_description: p.excerpt,
    meta_robots: 'index,follow',
    canonical_path: null,
    og_title: null,
    og_description: null,
    og_image_url: p.image,
    og_type: 'article',
    twitter_card: 'summary_large_image',
    focus_keyword: null,
    schema_json: null,
    created_at: p.publishedAt,
    updated_at: p.publishedAt,
  }))
}
